{{- define "crd_triggertemplate-triggers" -}}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggertemplates.triggers.tekton.dev
  labels: {{- include "helpers.labels.labels" (dict "Global" $ "Component" "tekton" "PartOf" "tekton-triggers") | nindent 4 }}
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: triggers.tekton.dev
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: TriggerTemplate
    plural: triggertemplates
    singular: triggertemplate
    shortNames:
      - tt
    categories:
      - tekton
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "crd_triggertemplate-triggers" ) }}
