{{- if $.Values.manifests.deployment_controller }}
{{- $mount_controller := $.Values.pod.mounts.tekton_controller.tekton_controller -}}
{{- $mount_controller_init := $.Values.pod.mounts.tekton_controller.init_container -}}
{{- $serviceAccountName := "tekton-triggers-controller" -}}
{{- $applicationName := "tekton-triggers" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $applicationName }}-controller
  annotations:
    {{ tuple $ | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{- tuple $ $applicationName "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 4 }}
spec:
  replicas: {{ $.Values.pod.replicas.controller }}
  selector:
    matchLabels:
{{- tuple $ $applicationName "controller" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 6 }}
{{- tuple $ | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | nindent 2 }}
  template:
    metadata:
      labels:
{{- tuple $ $applicationName "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
{{- tuple $ | include "helm-toolkit.snippets.release_uuid" | nindent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
{{- tuple $ "tekton_triggers" "controller" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | nindent 8 }}
      nodeSelector:
        {{ $.Values.labels.tekton_controller.node_selector_key }}: {{ $.Values.labels.tekton_controller.node_selector_value }}
      terminationGracePeriodSeconds: {{ $.Values.pod.lifecycle.termination_grace_period.controller.timeout | default "30" }}
      initContainers:
{{- tuple $ "tekton_controller" $mount_controller_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | nindent 8 }}
      containers:
        - name: tekton-triggers-controller
{{- tuple $ "tekton_controller" | include "helm-toolkit.snippets.image" | nindent 10 }}
{{- tuple $ $.Values.pod.resources.tekton_controller | include "helm-toolkit.snippets.kubernetes_resources" | nindent 10 }}
          args:
          - -logtostderr
          - -stderrthreshold
          - {{ $.Values.conf.controller.stderrthreshold | quote }}
          - -el-image
          - {{ $.Values.images.tags.tekton_eventlistener | quote }}
          - -el-port
          - {{ $.Values.conf.controller.el_port | quote }}
          - -period-seconds
          - {{ $.Values.conf.controller.period_seconds | quote }}
          - -failure-threshold
          - {{ $.Values.conf.controller.failure_threshold | quote }}
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging-triggers
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability-triggers
            - name: METRICS_DOMAIN
              value: tekton.dev/triggers
{{- dict "envAll" $ "application" "tekton_triggers" "container" "controller" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
{{- if $mount_controller.volumeMounts }}
          volumeMounts:
{{ toYaml $mount_controller.volumeMounts | indent 12 }}
{{- end }}
{{- if $mount_controller.volumes }}
      volumes:
{{ toYaml $mount_controller.volumes | indent 8 }}
{{- else }}
      volumes: []
{{- end }}
{{- end }}
