{{- if $.Values.manifests.deployment_controller }}
{{- $serviceAccountName := "tekton-triggers-controller" -}}
{{- $applicationName := "tekton-triggers" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $applicationName }}-controller
  labels:
    release_group: {{ $.Values.release_group | default $.Release.Name }}
    application: "tekton-triggers"
    component: "controller"
spec:
  replicas: {{ $.Values.pod.replicas.controller }}
  selector:
    matchLabels:
      release_group: {{ $.Values.release_group | default $.Release.Name }}
      application: "tekton-triggers"
      component: "controller"
{{- with .Values.pod.lifecycle.upgrades.deployments }}
  revisionHistoryLimit: {{ .revision_history }}
  strategy:
    type: {{ .pod_replacement_strategy }}
  {{- if eq .pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .rolling_update.max_unavailable }}
      maxSurge: {{ .rolling_update.max_surge }}
  {{- end }}
{{- end }}
  template:
    metadata:
      labels:
        release_group: {{ $.Values.release_group | default $.Release.Name }}
        application: "tekton-triggers"
        component: "controller"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
{{- tuple $ "tekton_triggers" "controller" | include "tekton.pod_anti_affinity" | nindent 8 }}
      nodeSelector:
        {{ $.Values.labels.tekton_controller.node_selector_key }}: {{ $.Values.labels.tekton_controller.node_selector_value }}
      terminationGracePeriodSeconds: {{ $.Values.pod.lifecycle.termination_grace_period.controller.timeout | default "30" }}
      containers:
        - name: tekton-triggers-controller
          image: {{ index $.Values.images.tags.tekton_controller | quote }}
          imagePullPolicy: {{ $.Values.images.pull_policy }}
        {{- if $.Values.pod.resources.enabled }}
          resources:
{{ toYaml $.Values.pod.resources.tekton_controller | trim | indent 12 }}
        {{- end }}
          args:
          - -logtostderr
          - -stderrthreshold
          - {{ $.Values.conf.controller.stderrthreshold | quote }}
          - -el-image
          - {{ $.Values.images.tags.tekton_eventlistener | quote }}
          - -el-port
          - {{ $.Values.conf.controller.el_port | quote }}
          - -period-seconds
          - {{ $.Values.conf.controller.period_seconds | quote }}
          - -failure-threshold
          - {{ $.Values.conf.controller.failure_threshold | quote }}
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging-triggers
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability-triggers
            - name: METRICS_DOMAIN
              value: tekton.dev/triggers
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65532
      volumes: []
{{- end }}
