---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-webhook
  labels: {{- include "helpers.labels.labels" (dict "Global" $) | nindent 4 }}
spec:
  replicas: {{ $.Values.pod.replicas.webhook }}
  selector:
    matchLabels: {{- include "helpers.labels.matchLabels" (dict "Global" $) | nindent 6 }}
{{- with $.Values.pod.lifecycle.upgrades.deployments }}
  revisionHistoryLimit: {{ .revision_history }}
  strategy:
    type: {{ .pod_replacement_strategy }}
  {{- if eq .pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .rolling_update.max_unavailable }}
      maxSurge: {{ .rolling_update.max_surge }}
  {{- end }}
{{- end }}
  template:
    metadata:
      labels: {{- include "helpers.labels.labels" (dict "Global" $) | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: tekton-triggers-controller
      affinity:
{{- tuple $ "tekton_triggers" "webhook" | include "tekton.pod_anti_affinity" | nindent 8 }}
      nodeSelector:
{{- include "helpers.pod.node_selector" ( dict "Global" $ "Application" "tekton_webhook" ) | nindent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.pod.lifecycle.termination_grace_period.webhook.timeout | default "30" }}
      containers:
        - name: tekton-triggers-webhook
          image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "tekton_webhook" ) }}
          imagePullPolicy: {{ $.Values.images.pull.policy | quote }}
{{- include "helpers.container.resources" ( dict "Global" $ "Application" "tekton_webhook" ) | nindent 10 }}
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging-triggers
            - name: WEBHOOK_SERVICE_NAME
              value: tekton-triggers-webhook
            - name: WEBHOOK_SECRET_NAME
              value: triggers-webhook-certs
            - name: METRICS_DOMAIN
              value: tekton.dev/triggers
          ports:
            - name: metrics
              containerPort: {{ $.Values.params.endpoints.ports.metrics.port }}
            - name: profiling
              containerPort: {{ $.Values.params.endpoints.ports.profiling.port }}
            - name: https-webhook
              containerPort: {{ $.Values.params.endpoints.ports.webhook.target }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65532
      volumes: []
