---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-controller
  labels: {{- include "helpers.labels.labels" (dict "Global" $) | nindent 4 }}
spec:
  replicas: {{ $.Values.pod.replicas.controller }}
  selector:
    matchLabels: {{- include "helpers.labels.matchLabels" (dict "Global" $) | nindent 6 }}
{{- with .Values.pod.lifecycle.upgrades.deployments }}
  revisionHistoryLimit: {{ .revision_history }}
  strategy:
    type: {{ .pod_replacement_strategy }}
  {{- if eq .pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .rolling_update.max_unavailable }}
      maxSurge: {{ .rolling_update.max_surge }}
  {{- end }}
{{- end }}
  template:
    metadata:
      labels: {{- include "helpers.labels.labels" (dict "Global" $) | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: tekton-triggers-controller
      affinity:
{{- tuple $ "tekton_triggers" "controller" | include "tekton.pod_anti_affinity" | nindent 8 }}
      nodeSelector:
{{- include "helpers.pod.node_selector" ( dict "Global" $ "Application" "tekton_controller" ) | nindent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.pod.lifecycle.termination_grace_period.controller.timeout | default "30" }}
      containers:
        - name: tekton-triggers-controller
          image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "tekton_controller" ) }}
          imagePullPolicy: {{ $.Values.images.pull.policy | quote }}
{{- include "helpers.container.resources" ( dict "Global" $ "Application" "tekton_controller" ) | nindent 10 }}
          args:
          - -logtostderr
          - -stderrthreshold
          - {{ $.Values.config.controller.stderrthreshold | quote }}
          - -el-image
          - {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "tekton_eventlistener" ) }}
          - -el-port
          - {{ $.Values.config.controller.el_port | quote }}
          - -period-seconds
          - {{ $.Values.config.controller.period_seconds | quote }}
          - -failure-threshold
          - {{ $.Values.config.controller.failure_threshold | quote }}
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging-triggers
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability-triggers
            - name: METRICS_DOMAIN
              value: tekton.dev/triggers
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65532
      volumes: []
