{{- if .Values.manifests.poddisruptionbudget }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tekton-triggers
spec:
  minAvailable: {{ $.Values.pod.lifecycle.disruption_budget.dashboard.min_available }}
  selector:
    matchLabels:
      release_group: {{ $.Values.release_group | default $.Release.Name }}
      application: "tekton-triggers"
      component: "controller"
{{- end }}
