{{- if $.Values.manifests.rbac }}
{{- $component := "triggers" -}}
{{- $partof := "tekton-triggers" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $partof }}
  name: tekton-triggers-controller
  namespace: {{ $.Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $partof }}
  name: tekton-triggers-admin
rules:
  - apiGroups:
    - "*"
    resources:
    - configmaps
    - services
    - events
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    - deployments/finalizers
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - triggers.tekton.dev
    resources:
    - clustertriggerbindings
    - eventlisteners
    - triggerbindings
    - triggertemplates
    - triggers
    - eventlisteners/finalizers
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - triggers.tekton.dev
    resources:
    - clustertriggerbindings/status
    - eventlisteners/status
    - triggerbindings/status
    - triggertemplates/status
    - triggers/status
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $partof }}
  name: tekton-triggers-admin
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - tekton-triggers
    verbs:
    - use
  - apiGroups:
    - "*"
    resources:
    - secrets
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $partof }}
  name: tekton-triggers-controller-admin
roleRef:
  kind: ClusterRole
  name: tekton-triggers-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-controller
    namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-controller-admin
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-controller
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-triggers-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-aggregate-edit
  labels:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $partof }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clustertriggerbindings
      - eventlisteners
      - triggers
      - triggerbindings
      - triggertemplates
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-aggregate-view
  labels:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $partof }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clustertriggerbindings
      - eventlisteners
      - triggers
      - triggerbindings
      - triggertemplates
    verbs:
      - get
      - list
      - watch
{{- end }}
