---
apiVersion: v1
kind: Service
metadata:
  name: tekton-triggers-controller
spec:
  selector: {{- include "helpers.labels.matchLabels" (dict "Global" $) | nindent 4 }}
  {{- if $.Values.network.node_port.enabled }}
  type: NodePort
  {{- if $.Values.network.external_policy_local }}
  externalTrafficPolicy: Local
  {{- end }}
  {{- end }}
  ports:
  - name: http-metrics
    protocol: TCP
    port: {{ $.Values.params.endpoints.ports.metrics.port }}
    targetPort: {{ $.Values.params.endpoints.ports.metrics.port }}
    {{- if $.Values.network.node_port.enabled }}
    nodePort: {{ $.Values.network.node_port.port }}
    {{- end }}
