{{- if .Values.manifests.service_metrics }}
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-triggers-controller
spec:
  selector:
{{ tuple $ "tekton-triggers" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{- if $.Values.network.node_port.enabled }}
  type: NodePort
  {{- if $.Values.network.external_policy_local }}
  externalTrafficPolicy: Local
  {{- end }}
  {{- end }}
  ports:
  - name: http-metrics
    protocol: TCP
    port: {{ tuple "tekton-triggers" "internal" "metrics" $ | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    targetPort:  {{ tuple "tekton-triggers" "target" "metrics" $ | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if $.Values.network.node_port.enabled }}
    nodePort: {{ $.Values.network.node_port.port }}
    {{- end }}
{{- end }}
