{{- if .Values.manifests.service_webhook }}
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-triggers-webhook
spec:
  selector:
    release_group: {{ $.Values.release_group | default $.Release.Name }}
    application: "tekton-triggers"
    component: "webhook"
  {{- if $.Values.network.node_port.enabled }}
  type: NodePort
  {{- if $.Values.network.external_policy_local }}
  externalTrafficPolicy: Local
  {{- end }}
  {{- end }}
  ports:
  - name: https-webhook
    protocol: TCP
    port: {{ tuple "tekton-triggers" "internal" "webhook" $ | include "tekton.port_lookup" }}
    targetPort:  {{ tuple "tekton-triggers" "target" "webhook" $ | include "tekton.port_lookup" }}
    {{- if $.Values.network.node_port.enabled }}
    nodePort: {{ $.Values.network.node_port.port }}
    {{- end }}
{{- end }}
