apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertriggerbindings.triggers.tekton.dev
spec:
  group: triggers.tekton.dev
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: ClusterTriggerBinding
    plural: clustertriggerbindings
    singular: clustertriggerbinding
    shortNames:
      - ctb
    categories:
      - tekton
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
