---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggerbindings.triggers.tekton.dev
  labels:
    app.kubernetes.io/component: tekton
    app.kubernetes.io/name: triggerbindings
    app.kubernetes.io/part-of: tekton-triggers
spec:
  group: triggers.tekton.dev
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: TriggerBinding
    plural: triggerbindings
    singular: triggerbinding
    shortNames:
      - tb
    categories:
      - tekton
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
...
