---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggers.triggers.tekton.dev
  # for helm 2
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/component: tekton
    app.kubernetes.io/name: triggers
    app.kubernetes.io/part-of: tekton-triggers
spec:
  group: triggers.tekton.dev
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: Trigger
    plural: triggers
    singular: trigger
    shortNames:
      - tri
    categories:
      - tekton
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
...
