apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: triggertemplates.triggers.tekton.dev
  labels:
    app.kubernetes.io/part-of: tekton-triggers
spec:
  group: triggers.tekton.dev
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: TriggerTemplate
    plural: triggertemplates
    singular: triggertemplate
    shortNames:
      - tt
    categories:
      - tekton
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
