---
config:
  controller:
    period_seconds: 10
    failure_threshold: 1
    stderrthreshold: INFO
    el_port: 8080
  loglevel:
    controller: info
    eventlistener: info
    webhook: info
  observability:
    metrics.backend-destination: prometheus
  zap_logger_config:
    development: false
    encoderConfig:
      callerEncoder: ''
      callerKey: caller
      durationEncoder: ''
      levelEncoder: ''
      levelKey: level
      lineEnding: ''
      messageKey: msg
      nameKey: logger
      stacktraceKey: stacktrace
      timeEncoder: ''
      timeKey: ''
    encoding: json
    errorOutputPaths:
      - stderr
    level: info
    outputPaths:
      - stdout
    sampling:
      initial: 100
      thereafter: 100

params:
  endpoints:
    hostname: tekton-triggers
    ports:
      metrics:
        port: 9090
        scheme: http
      profiling:
        port: 8008
        scheme: http
      webhook:
        port: 443
        target: 8443
        scheme: https

images:
  applications:
    tekton_controller:
      name: tektoncd/triggers/cmd/controller
      repo: gcr.io/tekton-releases/github.com
      tag: v0.9.1
    tekton_eventlistener:
      name: tektoncd/triggers/cmd/eventlistenersink
      repo: gcr.io/tekton-releases/github.com
      tag: v0.9.1
    tekton_webhook:
      name: tektoncd/triggers/cmd/webhook
      repo: gcr.io/tekton-releases/github.com
      tag: v0.9.1
  pull:
    policy: IfNotPresent

node_labels:
  tekton_controller:
    - key: node-role.kubernetes.io/master
      value: ''
  tekton_webhook:
    - key: node-role.kubernetes.io/master
      value: ''

network:
  node_port:
    enabled: false
    port: 32000

pod:
  affinity:
    anti:
      topologyKey:
        default: kubernetes.io/hostname
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      weight:
        default: 10
  lifecycle:
    disruption_budget:
      dashboard:
        min_available: 0
    termination_grace_period:
      controller:
        timeout: 30
      webhook:
        timeout: 30
    upgrades:
      deployments:
        pod_replacement_strategy: RollingUpdate
        revision_history: 3
        rolling_update:
          max_surge: 3
          max_unavailable: 1
  replicas:
    controller: 1
    webhook: 1
  resources:
    enabled: false
    tekton_dashboard:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
release_group: null
