---
config:
  controller:
    period_seconds: 10
    failure_threshold: 1
    stderrthreshold: INFO
    el_port: 8080
  loglevel:
    controller: info
    eventlistener: info
    webhook: info
  observability:
    metrics.backend-destination: prometheus
  zap_logger_config:
    development: false
    encoderConfig:
      callerEncoder: ''
      callerKey: caller
      durationEncoder: ''
      levelEncoder: ''
      levelKey: level
      lineEnding: ''
      messageKey: msg
      nameKey: logger
      stacktraceKey: stacktrace
      timeEncoder: ''
      timeKey: ''
    encoding: json
    errorOutputPaths:
      - stderr
    level: info
    outputPaths:
      - stdout
    sampling:
      initial: 100
      thereafter: 100

params:
  endpoints:
    ports:
      metrics:
        port: 9090
        scheme: http
      profiling:
        port: 8008
        scheme: http
      webhook:
        port: 443
        target: 8443
        scheme: https

images:
  applications:
    tekton_controller:
      name: tektoncd/triggers/cmd/controller
      repo: gcr.io/tekton-releases/github.com
      tag: v0.9.1@sha256:89e105cacb853ef8866baf0e2f0030651ec719e9bdc7cf56972edbd68dbd4779
    tekton_eventlistener:
      name: tektoncd/triggers/cmd/eventlistenersink
      repo: gcr.io/tekton-releases/github.com
      tag: v0.9.1@sha256:b687fc18b818f6e031083735b1833e6db3ba18d5113cfdc1ec8eb3c980e0f67d
    tekton_webhook:
      name: tektoncd/triggers/cmd/webhook
      repo: gcr.io/tekton-releases/github.com
      tag: v0.9.1@sha256:496bea4b0524c21be6bfe4eb5e99f92119cea3e58a93ed06a76536d7a1d9032c
  pull:
    policy: IfNotPresent

node_labels:
  tekton_controller:
    - key: node-role.kubernetes.io/master
      value: ''
  tekton_webhook:
    - key: node-role.kubernetes.io/master
      value: ''

over_rides: {}
